all: myshell mypwd mycd myls mymkdir myrm mymv myps mytail grep history
myshell: assign3_16CS60R62.c
	gcc assign3_16CS60R62.c -o myshell.out
mypwd: mypwd.c
	gcc mypwd.c -o mypwd.out
mycd: mycd.c
	gcc mycd.c -o mycd.out
myls: myls.c
	gcc myls.c -o myls.out
mymkdir: mymkdir.c
	gcc mymkdir.c -o mymkdir.out
myrm: myrm.c
	gcc myrm.c -o myrm.out
mymv: mymv.c
	gcc mymv.c -o mymv.out
myps: myps.c
	gcc myps.c -o myps.out
mytail: mytail.c
	gcc mytail.c -o mytail.out
grep: grep.c
	gcc grep.c -o grep.out
history: history.c
	gcc history.c -o history.out
