all: myshell mypwd mycd myls mymkdir myrm mymv myps mytail grep history mysed  assign4b1 assign4b2 assign4b3
myshell: assign4_16CS60R62.c
	gcc assign4_16CS60R62.c -o assign4_16CS60R62.out
mypwd: mypwd.c
	gcc mypwd.c -o mypwd.out
mycd: mycd.c
	gcc mycd.c -o mycd.out
myls: myls.c
	gcc myls.c -o myls.out
mymkdir: mymkdir.c
	gcc mymkdir.c -o mymkdir.out
myrm: myrm.c
	gcc myrm.c -o myrm.out
mymv: mymv.c
	gcc mymv.c -o mymv.out
myps: myps.c
	gcc myps.c -o myps.out
mytail: mytail.c
	gcc mytail.c -o mytail.out
grep: grep.c
	gcc grep.c -o grep.out
history: history.c
	gcc history.c -o history.out
mysed: mysed.c
	gcc mysed.c -o mysed.out
assign4b1: assign4b1.c
	gcc assign4b1.c -o assign4b1.out
assign4b2: assign4b2.c
	gcc assign4b2.c -o assign4b2.out
assign4b3: assign4b3.c
	gcc assign4b3.c -o assign4b3.out
